version: "3.0"

services:
  devopsdb:
    image: manikantathalari/auto:db
    ports:
      - "3333:3306"
    deploy:
      replicas: 3
    networks:
      - mynetwork

  application:
    image: manikantathalari/auto:app
    ports:
      - "2222:8080"
    deploy:
      replicas: 3
    depends_on:
      - devopsdb
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: overlay
