version: "3.9"

services:
  devopsdb:
    image: manikantathalari/auto:db
    ports:
      - "3306:3306"
    networks:
      - mynetwork

  application:
    image: manikantathalari/auto:app
    ports:
      - "1234:8080"
    depends_on:
      - devopsdb
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: overlay
